// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/news": {
    params: {};
  };
  "/news/:id": {
    params: {
      "id": string;
    };
  };
  "/contract": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/news" | "/news/:id" | "/contract";
  };
  "./routes/layout/layout.tsx": {
    id: "routes/layout/layout";
    page: "/" | "/news" | "/news/:id" | "/contract";
  };
  "./routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/news.tsx": {
    id: "routes/news";
    page: "/news";
  };
  "routes/news-detail.tsx": {
    id: "routes/news-detail";
    page: "/news/:id";
  };
  "routes/contract.tsx": {
    id: "routes/contract";
    page: "/contract";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/layout/layout": typeof import("./app/./routes/layout/layout.tsx");
  "routes/home": typeof import("./app/./routes/home.tsx");
  "routes/news": typeof import("./app/routes/news.tsx");
  "routes/news-detail": typeof import("./app/routes/news-detail.tsx");
  "routes/contract": typeof import("./app/routes/contract.tsx");
};